In [79]:
import pandas as pd
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import tensorflow as tf
import pickle
from sklearn.model_selection import train_test_split    

data = pd.read_csv("D:\\Teja\\python_Automation\\pythonProject\\ANN_Regression_Data\\regression_sample.csv")
print(data.info())
print(data.head())


input=data.drop('price',axis=1)
target=data['price']

input.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   area_sqft              200 non-null    int64
 1   bedrooms               200 non-null    int64
 2   bathrooms              200 non-null    int64
 3   age_years              200 non-null    int64
 4   distance_from_city_km  200 non-null    int64
 5   parking                200 non-null    int64
 6   furnishing             200 non-null    object
 7   location               200 non-null    object
 8   price                  200 non-null    int64
dtypes: int64(7), object(2)
memory usage: 14.2+ KB
None
   area_sqft  bedrooms  bathrooms  age_years  distance_from_city_km  parking  \
0       1360         1          1         17                     22        0
1       4272         1          1          7                     30        2
2       3592         3          2         13                     17        1
3        966         3          2          9                     26        0
4       4926         3          3         27                     36        1

    furnishing  location     price
0    Furnished     Urban   6400000
1    Furnished  Suburban  17200000
2    Furnished     Urban  22500000
3  Unfurnished     Rural   1450000
4    Furnished  Suburban  19300000

,area_sqft,bedrooms,bathrooms,age_years,distance_from_city_km,parking,furnishing,location
0,1360,1,1,17,22,0,Furnished,Urban
1,4272,1,1,7,30,2,Furnished,Suburban
2,3592,3,2,13,17,1,Furnished,Urban
3,966,3,2,9,26,0,Unfurnished,Rural
4,4926,3,3,27,36,1,Furnished,Suburban

In [63]:
onehot_encoder = OneHotEncoder(handle_unknown='ignore')
input_encoded = onehot_encoder.fit_transform(input[['furnishing', 'location']])
encoded=pd.DataFrame(input_encoded.toarray(), columns=onehot_encoder.get_feature_names_out(['furnishing', 'location']))
final = pd.concat([input.drop(['furnishing', 'location'], axis=1), encoded], axis=1)
final.head()

,area_sqft,bedrooms,bathrooms,age_years,distance_from_city_km,parking,furnishing_Furnished,furnishing_Semi-Furnished,furnishing_Unfurnished,location_Rural,location_Suburban,location_Urban
0,1360,1,1,17,22,0,1.0,0.0,0.0,0.0,0.0,1.0
1,4272,1,1,7,30,2,1.0,0.0,0.0,0.0,1.0,0.0
2,3592,3,2,13,17,1,1.0,0.0,0.0,0.0,0.0,1.0
3,966,3,2,9,26,0,0.0,0.0,1.0,1.0,0.0,0.0
4,4926,3,3,27,36,1,1.0,0.0,0.0,0.0,1.0,0.0

In [64]:
import pickle

# Save the encoders
with open('one_hot_encoder.pkl', 'wb') as f:
    pickle.dump(onehot_encoder, f)

print("Encoders saved successfully.")

Encoders saved successfully.

In [65]:
x_train, x_test, y_train, y_test = train_test_split(final, target, test_size=0.2, random_state=42)

# Scale features
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled  = scaler.transform(x_test)

# Scale target (price) — important for regression with large values
target_scaler = StandardScaler()
y_train_scaled = target_scaler.fit_transform(y_train.values.reshape(-1, 1))
y_test_scaled  = target_scaler.transform(y_test.values.reshape(-1, 1))

print("x_train shape:", x_train_scaled.shape)
print("y_train scaled sample:", y_train_scaled[:3])

x_train shape: (160, 12)
y_train scaled sample: [[-0.33056708]
 [ 2.05799968]
 [-0.35241373]]

In [66]:
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

with open('target_scaler.pkl', 'wb') as f:
    pickle.dump(target_scaler, f)

print("Scalers saved.")

Scalers saved.

In [67]:
import tensorflow as tf
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense, Dropout

# Simple model — best for small datasets (30 rows)
model = Sequential([
    Dense(32, activation='relu', input_shape=(x_train_scaled.shape[1],)),
    Dropout(0.1),
    Dense(16, activation='relu'),
    Dense(1)
])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              loss='mean_squared_error',
              metrics=['mean_absolute_error'])
model.summary()

d:\Teja\python_Automation\pythonProject\Teja_repo\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_19 (Dense)                │ (None, 32)             │           416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 961 (3.75 KB)

 Trainable params: 961 (3.75 KB)

 Non-trainable params: 0 (0.00 B)

In [68]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
early_stopping       = EarlyStopping(monitor='val_loss', patience=30, restore_best_weights=True)
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [69]:
history = model.fit(x_train_scaled, y_train_scaled,
                    validation_data=(x_test_scaled, y_test_scaled),
                    epochs=100, batch_size=4,
                    callbacks=[early_stopping, tensorboard_callback],
                    verbose=1)
model.save('ann_regression_model.keras')
print("Model saved.")

Epoch 1/100

40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 1.1495 - mean_absolute_error: 0.8875 - val_loss: 0.9471 - val_mean_absolute_error: 0.8184
Epoch 2/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.8818 - mean_absolute_error: 0.7626 - val_loss: 0.7457 - val_mean_absolute_error: 0.7125
Epoch 3/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.7502 - mean_absolute_error: 0.7106 - val_loss: 0.5886 - val_mean_absolute_error: 0.6259
Epoch 4/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.5789 - mean_absolute_error: 0.6035 - val_loss: 0.4410 - val_mean_absolute_error: 0.5323
Epoch 5/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.3958 - mean_absolute_error: 0.4903 - val_loss: 0.3033 - val_mean_absolute_error: 0.4168
Epoch 6/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2986 - mean_absolute_error: 0.4226 - val_loss: 0.1857 - val_mean_absolute_error: 0.3159
Epoch 7/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2445 - mean_absolute_error: 0.3669 - val_loss: 0.1295 - val_mean_absolute_error: 0.2673
Epoch 8/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1471 - mean_absolute_error: 0.2869 - val_loss: 0.0909 - val_mean_absolute_error: 0.2247
Epoch 9/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1050 - mean_absolute_error: 0.2552 - val_loss: 0.0711 - val_mean_absolute_error: 0.1989
Epoch 10/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1041 - mean_absolute_error: 0.2535 - val_loss: 0.0565 - val_mean_absolute_error: 0.1736
Epoch 11/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1052 - mean_absolute_error: 0.2515 - val_loss: 0.0523 - val_mean_absolute_error: 0.1681
Epoch 12/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0822 - mean_absolute_error: 0.2190 - val_loss: 0.0418 - val_mean_absolute_error: 0.1492
Epoch 13/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0770 - mean_absolute_error: 0.2058 - val_loss: 0.0362 - val_mean_absolute_error: 0.1406
Epoch 14/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0701 - mean_absolute_error: 0.1978 - val_loss: 0.0337 - val_mean_absolute_error: 0.1373
Epoch 15/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0533 - mean_absolute_error: 0.1704 - val_loss: 0.0352 - val_mean_absolute_error: 0.1442
Epoch 16/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0701 - mean_absolute_error: 0.1852 - val_loss: 0.0303 - val_mean_absolute_error: 0.1325
Epoch 17/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0753 - mean_absolute_error: 0.1989 - val_loss: 0.0273 - val_mean_absolute_error: 0.1229
Epoch 18/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0747 - mean_absolute_error: 0.1841 - val_loss: 0.0247 - val_mean_absolute_error: 0.1204
Epoch 19/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0462 - mean_absolute_error: 0.1581 - val_loss: 0.0283 - val_mean_absolute_error: 0.1255
Epoch 20/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0818 - mean_absolute_error: 0.1886 - val_loss: 0.0229 - val_mean_absolute_error: 0.1134
Epoch 21/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0530 - mean_absolute_error: 0.1769 - val_loss: 0.0221 - val_mean_absolute_error: 0.1158
Epoch 22/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0377 - mean_absolute_error: 0.1408 - val_loss: 0.0237 - val_mean_absolute_error: 0.1141
Epoch 23/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0493 - mean_absolute_error: 0.1478 - val_loss: 0.0210 - val_mean_absolute_error: 0.1138
Epoch 24/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0396 - mean_absolute_error: 0.1526 - val_loss: 0.0230 - val_mean_absolute_error: 0.1233
Epoch 25/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0492 - mean_absolute_error: 0.1642 - val_loss: 0.0174 - val_mean_absolute_error: 0.1058
Epoch 26/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0432 - mean_absolute_error: 0.1656 - val_loss: 0.0212 - val_mean_absolute_error: 0.1158
Epoch 27/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0467 - mean_absolute_error: 0.1512 - val_loss: 0.0173 - val_mean_absolute_error: 0.0989
Epoch 28/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0427 - mean_absolute_error: 0.1456 - val_loss: 0.0159 - val_mean_absolute_error: 0.0980
Epoch 29/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0377 - mean_absolute_error: 0.1433 - val_loss: 0.0174 - val_mean_absolute_error: 0.1026
Epoch 30/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0376 - mean_absolute_error: 0.1318 - val_loss: 0.0165 - val_mean_absolute_error: 0.1023
Epoch 31/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0479 - mean_absolute_error: 0.1615 - val_loss: 0.0168 - val_mean_absolute_error: 0.1000
Epoch 32/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0363 - mean_absolute_error: 0.1416 - val_loss: 0.0147 - val_mean_absolute_error: 0.0919
Epoch 33/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0505 - mean_absolute_error: 0.1444 - val_loss: 0.0126 - val_mean_absolute_error: 0.0815
Epoch 34/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0357 - mean_absolute_error: 0.1253 - val_loss: 0.0109 - val_mean_absolute_error: 0.0785
Epoch 35/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0344 - mean_absolute_error: 0.1382 - val_loss: 0.0126 - val_mean_absolute_error: 0.0839
Epoch 36/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0438 - mean_absolute_error: 0.1404 - val_loss: 0.0141 - val_mean_absolute_error: 0.0924
Epoch 37/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0440 - mean_absolute_error: 0.1585 - val_loss: 0.0117 - val_mean_absolute_error: 0.0766
Epoch 38/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0271 - mean_absolute_error: 0.1173 - val_loss: 0.0119 - val_mean_absolute_error: 0.0818
Epoch 39/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0344 - mean_absolute_error: 0.1394 - val_loss: 0.0117 - val_mean_absolute_error: 0.0801
Epoch 40/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0410 - mean_absolute_error: 0.1490 - val_loss: 0.0093 - val_mean_absolute_error: 0.0718
Epoch 41/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0274 - mean_absolute_error: 0.1292 - val_loss: 0.0103 - val_mean_absolute_error: 0.0729
Epoch 42/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0280 - mean_absolute_error: 0.1203 - val_loss: 0.0105 - val_mean_absolute_error: 0.0746
Epoch 43/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0554 - mean_absolute_error: 0.1609 - val_loss: 0.0100 - val_mean_absolute_error: 0.0743
Epoch 44/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0314 - mean_absolute_error: 0.1357 - val_loss: 0.0116 - val_mean_absolute_error: 0.0841
Epoch 45/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0352 - mean_absolute_error: 0.1335 - val_loss: 0.0103 - val_mean_absolute_error: 0.0771
Epoch 46/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0326 - mean_absolute_error: 0.1348 - val_loss: 0.0113 - val_mean_absolute_error: 0.0835
Epoch 47/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0302 - mean_absolute_error: 0.1271 - val_loss: 0.0097 - val_mean_absolute_error: 0.0743
Epoch 48/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0327 - mean_absolute_error: 0.1262 - val_loss: 0.0109 - val_mean_absolute_error: 0.0800
Epoch 49/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0291 - mean_absolute_error: 0.1229 - val_loss: 0.0115 - val_mean_absolute_error: 0.0852
Epoch 50/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0474 - mean_absolute_error: 0.1354 - val_loss: 0.0091 - val_mean_absolute_error: 0.0733
Epoch 51/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0360 - mean_absolute_error: 0.1397 - val_loss: 0.0120 - val_mean_absolute_error: 0.0832
Epoch 52/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0254 - mean_absolute_error: 0.1157 - val_loss: 0.0138 - val_mean_absolute_error: 0.0931
Epoch 53/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0274 - mean_absolute_error: 0.1250 - val_loss: 0.0107 - val_mean_absolute_error: 0.0791
Epoch 54/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0379 - mean_absolute_error: 0.1397 - val_loss: 0.0081 - val_mean_absolute_error: 0.0699
Epoch 55/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0211 - mean_absolute_error: 0.1097 - val_loss: 0.0090 - val_mean_absolute_error: 0.0716
Epoch 56/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0280 - mean_absolute_error: 0.1241 - val_loss: 0.0102 - val_mean_absolute_error: 0.0740
Epoch 57/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0201 - mean_absolute_error: 0.1023 - val_loss: 0.0116 - val_mean_absolute_error: 0.0877
Epoch 58/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0192 - mean_absolute_error: 0.0944 - val_loss: 0.0130 - val_mean_absolute_error: 0.0883
Epoch 59/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0209 - mean_absolute_error: 0.1038 - val_loss: 0.0142 - val_mean_absolute_error: 0.0892
Epoch 60/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0258 - mean_absolute_error: 0.1099 - val_loss: 0.0153 - val_mean_absolute_error: 0.1010
Epoch 61/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0242 - mean_absolute_error: 0.1177 - val_loss: 0.0091 - val_mean_absolute_error: 0.0713
Epoch 62/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0255 - mean_absolute_error: 0.1145 - val_loss: 0.0099 - val_mean_absolute_error: 0.0788
Epoch 63/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0213 - mean_absolute_error: 0.0992 - val_loss: 0.0121 - val_mean_absolute_error: 0.0879
Epoch 64/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0343 - mean_absolute_error: 0.1208 - val_loss: 0.0189 - val_mean_absolute_error: 0.1088
Epoch 65/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0267 - mean_absolute_error: 0.1188 - val_loss: 0.0134 - val_mean_absolute_error: 0.0861
Epoch 66/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0245 - mean_absolute_error: 0.1026 - val_loss: 0.0122 - val_mean_absolute_error: 0.0852
Epoch 67/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0275 - mean_absolute_error: 0.1117 - val_loss: 0.0137 - val_mean_absolute_error: 0.0827
Epoch 68/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0261 - mean_absolute_error: 0.1022 - val_loss: 0.0109 - val_mean_absolute_error: 0.0720
Epoch 69/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0197 - mean_absolute_error: 0.1059 - val_loss: 0.0124 - val_mean_absolute_error: 0.0790
Epoch 70/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0189 - mean_absolute_error: 0.0934 - val_loss: 0.0122 - val_mean_absolute_error: 0.0840
Epoch 71/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0189 - mean_absolute_error: 0.0995 - val_loss: 0.0094 - val_mean_absolute_error: 0.0702
Epoch 72/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0167 - mean_absolute_error: 0.0952 - val_loss: 0.0116 - val_mean_absolute_error: 0.0816
Epoch 73/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0257 - mean_absolute_error: 0.1116 - val_loss: 0.0110 - val_mean_absolute_error: 0.0755
Epoch 74/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0203 - mean_absolute_error: 0.1068 - val_loss: 0.0113 - val_mean_absolute_error: 0.0812
Epoch 75/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0157 - mean_absolute_error: 0.0912 - val_loss: 0.0103 - val_mean_absolute_error: 0.0796
Epoch 76/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0193 - mean_absolute_error: 0.0933 - val_loss: 0.0104 - val_mean_absolute_error: 0.0780
Epoch 77/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0129 - mean_absolute_error: 0.0836 - val_loss: 0.0131 - val_mean_absolute_error: 0.0924
Epoch 78/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0165 - mean_absolute_error: 0.0926 - val_loss: 0.0082 - val_mean_absolute_error: 0.0687
Epoch 79/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0151 - mean_absolute_error: 0.0884 - val_loss: 0.0095 - val_mean_absolute_error: 0.0693
Epoch 80/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0245 - mean_absolute_error: 0.1115 - val_loss: 0.0100 - val_mean_absolute_error: 0.0768
Epoch 81/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0187 - mean_absolute_error: 0.1003 - val_loss: 0.0092 - val_mean_absolute_error: 0.0702
Epoch 82/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0184 - mean_absolute_error: 0.1010 - val_loss: 0.0095 - val_mean_absolute_error: 0.0758
Epoch 83/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0143 - mean_absolute_error: 0.0915 - val_loss: 0.0096 - val_mean_absolute_error: 0.0712
Epoch 84/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0176 - mean_absolute_error: 0.0909 - val_loss: 0.0115 - val_mean_absolute_error: 0.0814
Model saved.

In [71]:
#load tensorboard extension
%load_ext tensorboard
%tensorboard --logdir logs/fit

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6008 (pid 24156), started 0:03:15 ago. (Use '!kill 24156' to kill it.)

In [ ]:
# load the pickle


with open('scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)
with open('target_scaler.pkl', 'rb') as f:
    target_scaler = pickle.load(f)

In [73]:
#Eveluate the model on test data
test_loss, test_mae = model.evaluate(x_test_scaled, y_test_scaled, verbose=0)
print(f"Test Loss: {test_loss:.4f}, Test MAE: {test_mae:.4f}")

Test Loss: 0.0081, Test MAE: 0.0699

In [ ]:
import pandas as pd

# Input new house data for prediction
input_data = {
    'area_sqft':             [1500, 3200],
    'bedrooms':              [3,    5],
    'bathrooms':             [2,    4],
    'age_years':             [5,    2],
    'distance_from_city_km': [10,   3],
    'parking':               [1,    2],
    'furnishing':            ['Furnished', 'Semi-Furnished'],
    'location':              ['Suburban',  'Urban']
}

input_df = pd.DataFrame(input_data)

# Step 1: One-hot encode furnishing and location
enc = onehot_encoder.transform(input_df[['furnishing', 'location']])
enc_df = pd.DataFrame(enc.toarray(), columns=onehot_encoder.get_feature_names_out(['furnishing', 'location']))
input_final = pd.concat([input_df.drop(['furnishing', 'location'], axis=1), enc_df], axis=1)

# Step 2: Scale features
input_scaled = scaler.transform(input_final)

# Step 3: Predict
pred_scaled = model.predict(input_scaled)

# Step 4: Inverse transform to get actual rupee price
pred_actual = target_scaler.inverse_transform(pred_scaled)

print("=" * 50)
for i in range(len(pred_actual)):
    print(f"House {i+1}:")
    print(f"  Area       : {input_data['area_sqft'][i]} sqft")
    print(f"  Location   : {input_data['location'][i]}")
    print(f"  Furnishing : {input_data['furnishing'][i]}")
    print(f"  Predicted  : ₹{pred_actual[i][0]:,.0f}")
    print(f"  Scaled out : {pred_scaled[i][0]:.4f}")
print("=" * 50)
print(f"\nTarget scaler mean : ₹{target_scaler.mean_[0]:,.0f}")
print(f"Target scaler std  : ₹{target_scaler.scale_[0]:,.0f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 188ms/step
Predicted Prices: [6.6164345e+06 1.8754382e+07]